### ISSUE TITLE
x(), y() accessors not working as expected?

### ISSUE THREAD

**Issue by konstantinosvilaetis** [d3/d3-quadtree#27]
I am trying to make a flock simulation and using a quadtree to limit calculations per iteration.

When I create the quadtree as:
`const quadtree = d3.quadtree(boids.map((b) => [b.position.x, b.position.y]));`
the data is loaded correctly.

![Screenshot 2020-05-02 at 17 38 11](https://user-images.githubusercontent.com/30746336/80870033-c7e95a80-8c9b-11ea-8317-2dcf95f07ab5.png)

However, when I substitute it with:
`const quadtree = d3.quadtree(boids).x((b) => b.position.x).y((b) => b.position.y);`
the `quadtree.data() = []`;

Isn't this an issue with the x(), y() accessors? Or am I doing sth wrong? 

Version: 5.16.0

**Comment by mbostock** [comment]
It’s an order-of-operations problem. You’re passing the data before specifying the accessors.

Try this:

```js
d3.quadtree(boids, b => b.position.x, b => b.position.y)
```

Or this:

```js
d3.quadtree()
    .x(b => b.position.x)
    .y(b => b.position.y)
    .addAll(boids)
```

**Comment by konstantinosvilaetis** [comment]
thanks very much, they both work, sorry for the trouble!
