### ISSUE TITLE
findInCircle?

### ISSUE THREAD

**Issue by Fil** [d3/d3-quadtree#30]
I have revised findAll (see the discussion in #18):
https://observablehq.com/d/ff2450667f13132f

also prepared a quadtree.findInPolygon() algorithm (which was fun!) (ping @gka)
https://observablehq.com/d/54a6e96b6630b0d9

<del>I think both functions could be added to this module—however findInPolygon adds a dependency on a dedicated functions in d3.polygon (polygonIntersect, https://github.com/d3/d3-polygon/issues/28), that doesn't yet exist, so don't expect it to land too soon (if at all).</del>

Anyways it's already usable by copying the code, and it would be great to have tests and feedback.

**Comment by curran** [comment]
This is very cool work!

**Comment by Fil** [comment]
findInPolygon was very fun to write but unfortunately, in my tests, even with a million data points it's still faster (or about the same speed) to run the baseline algorithm `for (const d of data) { polygonContains(d) }` than to use a quadtree. findAll (now renamed findInCircle) is probably similar, but its code footprint is much smaller.

**Comment by Fil** [comment]
Published as an example of a visit https://observablehq.com/@d3/quadtree-findincircle

**Comment by curran** [comment]
I see #32 was closed without being merged. Why is that?

IMO the feature would be a useful addition to `d3-quadtree`.

**Comment by Fil** [comment]
I've closed #32 because I felt the code would be more useful as an example, rather than as another method added to the API. If people start using it en masse, it might change, but in the meantime what we probably need to do is to link to examples and show that quadtree.visit is not as intimidating as it might seem.

**Comment by curran** [comment]
Got it. Thanks!
