### ISSUE TITLE
Return coincident points with find

### ISSUE THREAD

**Issue by cguastini** [d3/d3-quadtree#38]
Currently, ```quadtree.find``` returns one point even if many coincident points are in the tree.
```js
var quadtree = d3.quadtree([[1, 1, "red"], [1, 1, "green"], [0, 0, "blue"]]);
var result = quadtree.find(1,1);
```
```result``` will be ```[1, 1, "green"]```. 

I'm working with a point-of-interest dataset that contains many locations at the same coordinates (e.g., stores in the same mall), and my desired behavior is to return all of the points at that one location ```[[1, 1, "green"], [1, 1, "red"]]```. I have created a [fork](https://github.com/cguastini/d3-quadtree) that does this with a couple minor changes. I would create a PR, but they are breaking changes because the results are now an array rather than a single value. It may not be worth trying to merge as is.

**Comment by Fil** [comment]
quadtree.find is meant to be simple; in this use case you can visit the quadtree with a custom function (there's no need to patch d3-quadtree).

Here's a similar example https://observablehq.com/d/ff2450667f13132f#findInCircle

**Comment by cguastini** [comment]
My patch didn’t feel like the best solution because of the change in quadtree.find behavior, so thank you for the alternative approach!
